### ISSUE TITLE
tag current develop branch pls

### ISSUE THREAD

**Issue by huiyiqun** [tinsukE/icekick#2]
Or I could not get latest code from jitpack.io or use `lateState`

**Comment by tinsukE** [comment]
Hi there, you can use the hash for the last commit instead of a version in
a jitpack dependency, like:

compile 'com.github.tinsukE:icekick:6bf621c2c2'

I won't be able to tag it soon because I'm on holidays.

**Comment by tinsukE** [comment]
`lateState` is available on the 0.2 release, check it out!
